In [1]:
import scqubits as scq
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
from time import time
import time as tm
from tqdm.notebook import tqdm
import primme as pr

 /var/folders/1p/rx6gwn090ql46kwfqwwf4_6c0000gn/T/ipykernel_1385/2402225946.py: 8

In [2]:
#from Spring2023 import scipy_option_tester
from Spring2023 import primme_benchmarker

In [5]:
cos2phi = scq.Cos2PhiQubit.create()

Output()

In [4]:
cos2phi.hamiltonian



<bound method Cos2PhiQubit.hamiltonian of Cos2PhiQubit(**{'EJ': 15.0, 'ECJ': 2.0, 'EL': 1.0, 'EC': 0.04, 'dL': 0.6, 'dCJ': 0.0, 'dEJ': 0.0, 'flux': 0.5, 'ng': 0.0, 'ncut': 7, 'zeta_cut': 30, 'phi_cut': 7, 'truncated_dim': 6, 'id_str': 'Cos2PhiQubit_1'})>

In [7]:
matrix = primme_benchmarker(cos2phi, ["E_J", "n_cut", "E_L"], [np.linspace(13.5, 16.5, 5), np.array([20,30,40,50,60]), np.linspace(.5, 1.5, 5)], 1)


In [10]:
matrix

array([[[0.54831569, 0.3928469 , 0.30976903, 0.42099136, 0.23807473],
        [0.33957392, 0.63671496, 0.36025991, 0.34444584, 0.44387979],
        [0.33948296, 0.5133865 , 0.36736521, 0.37956477, 0.49382635],
        [0.45558623, 0.32043465, 0.26171748, 1.02273117, 0.55202513],
        [0.38579421, 0.42533576, 0.430917  , 0.52079899, 0.39688548]],

       [[0.43614795, 0.35995556, 0.42653563, 0.47489521, 0.35356723],
        [0.42403573, 0.44533946, 0.43434739, 0.36707536, 0.43520077],
        [0.48439093, 0.36961624, 0.30591957, 0.33646983, 0.35191182],
        [0.67466492, 0.43617062, 0.38065864, 0.49644751, 0.22070042],
        [0.56686537, 0.45566005, 0.29982524, 0.45563571, 0.43886835]],

       [[0.36944599, 0.46466282, 0.2996769 , 0.44121327, 0.31683469],
        [0.38532977, 0.60347074, 0.49735955, 0.28488786, 0.61636539],
        [0.35862708, 0.41567602, 0.4679054 , 0.30130237, 0.31864175],
        [0.29665193, 0.55188363, 0.33161907, 0.41922547, 0.33094226],
        [0.32905

In [9]:
np.save("primme_benchmarker_test", matrix)

In [12]:
primme_benchmarker??


Signature: primme_benchmarker(qubit, shape, N, energies, ncuts)
Docstring: <no docstring>
Source:   
def primme_benchmarker(qubit, shape, avg_num, param_1, a, b, param_2, c, d, file_name):
    # shape: tuple with size of matrix (m,n)
    # avg_num: number of iterations for averaging
    # param_1: first parameter to be varied
    # a: cutoff for p1
    # b: cutoff for p1
    # param_2:
    # c: cutoff
    # d: cutoff
    # file_name:
    times_a = np.empty(shape = shape)
    times_b = np.empty(shape = shape)
    param_1_list = np.linspace(a, b, shape[0])
    param_2_list = np.linspace(c, d, shape[1])
    for index_1, energy in tqdm(enumerate(param_1_list)):
        qubit.__dict__[param_1] = energy
        for index_2, p in enumerate(param_2):
            qubit.__dict__[param_2] = p
            #for ncut in qubit.cutoff_names:
                #qubit.__dict__["_" + ncut] = dim
            hamiltonian = qubit.hamiltonian()
            start_time_1 = time()
            for _ in range(avg_n

In [13]:
list1 = [1,2,3]
list2 = [.5, .6]


In [15]:
np.meshgrid(list1, list2, 2*list2)

[array([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],
 
        [[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]]]),
 array([[[0.5, 0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5, 0.5],
         [0.5, 0.5, 0.5, 0.5]],
 
        [[0.6, 0.6, 0.6, 0.6],
         [0.6, 0.6, 0.6, 0.6],
         [0.6, 0.6, 0.6, 0.6]]]),
 array([[[0.5, 0.6, 0.5, 0.6],
         [0.5, 0.6, 0.5, 0.6],
         [0.5, 0.6, 0.5, 0.6]],
 
        [[0.5, 0.6, 0.5, 0.6],
         [0.5, 0.6, 0.5, 0.6],
         [0.5, 0.6, 0.5, 0.6]]])]